# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.1.2
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Modules aiming to support e-commerce specific needs. This includes
  all the new website_sale related modules included in version 12.0.
repo_name: E-commerce modules
repo_slug: cie-e-commerce
travis_apt_packages: []
travis_apt_sources: []
