# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.0.12
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups: []
repo_description: Modules aiming to support e-commerce-specific needs. This includes
  all the new website_sale-related modules included in version 12.0.
repo_name: E-commerce modules
repo_slug: cie-e-commerce
repo_website: https://coopiteasy.be
travis_apt_packages: []
travis_apt_sources: []
